# Generated by Django 4.1.7 on 2023-03-26 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_created_at_alter_blog_introduce_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_at',
        ),
    ]
