# Generated by Django 4.1.7 on 2023-03-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='생일'),
        ),
    ]
